services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /tmp
    network_mode: bridge
    ports:
      - '8096:8096'
    volumes:
      - /opt/backups/jellyfin:/config
      - /mnt/gdrive:/media/gdrive:ro
    environment:
      - TZ=America/Santiago
      - PUID=1000
      - PGID=1000
    deploy:
      resources:
        limits:
          memory: 1500M
        reservations:
          memory: 512M
    memswap_limit: 1500m
    cpus: "1.0"
    cpu_shares: 128
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'


volumes:
  jellyfin_config:
